name: "releases"
 
on:
  push:
     branches:
       - main
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: create release
      run: |
         curl -L \
         -X POST \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer 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"\
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/sherif7z7/Nextcloud-deployment-in-Kubernetes/releases \
         -d '{"tag_name":"v1.0.0","target_commitish":"master","name":"v1.0.0","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
